export const NavLinkList = [
  { title: 'Work', path: '/work' },
  { title: 'CV', path: '/cv' },
  { title: 'Contact', path: '/contact' },
];

export const slideshowImages = [
  { src: '/images/slide1.jpg' },
  { src: '/images/slide2.jpg', position: '40% 0' },
  { src: '/images/slide3.jpg' },
  { src: '/images/slide4.jpg', position: '0 70%' },
  { src: '/images/slide5.jpg' },
  { src: '/images/slide6.jpg' },
  { src: '/images/slide7.jpg', position: '46% 0' },
  { src: '/images/slide8.jpg' },
  { src: '/images/slide9.jpg' },
];

export const sections = [
  [
    '/images/concert/concert1.jpeg',
    '/images/concert/concert2.jpeg',
    '/images/concert/concert3.jpeg',
    '/images/concert/concert4.jpeg',
    '/images/concert/concert5.jpeg',
    '/images/concert/concert6.jpeg',
    '/images/concert/concert7.jpeg',
    '/images/concert/concert8.jpeg',
    '/images/concert/concert9.jpeg',
    '/images/concert/concert10.jpeg',
    '/images/concert/concert11.jpeg',
  ],
  [
    '/images/people/people1.jpeg',
    '/images/people/people2.jpeg',
    '/images/people/people3.jpeg',
    '/images/people/people4.jpeg',
    '/images/people/people5.jpeg',
    '/images/people/people6.jpeg',
    '/images/people/people7.jpeg',
    '/images/people/people8.jpeg',
    '/images/people/people9.jpeg',
    '/images/people/people10.jpeg',
    '/images/people/people11.jpeg',
    '/images/people/people12.jpeg',
  ],
  [
    '/images/travel/travel1.jpeg',
    '/images/travel/travel2.jpeg',
    '/images/travel/travel3.jpeg',
    '/images/travel/travel4.jpeg',
    '/images/travel/travel5.jpeg',
    '/images/travel/travel6.jpeg',
    '/images/travel/travel7.jpeg',
    '/images/travel/travel8.jpeg',
    '/images/travel/travel9.jpeg',
    '/images/travel/travel10.jpeg',
    '/images/travel/travel11.jpeg',
    '/images/travel/travel12.jpeg',
  ],
  [
    '/images/film/film1.jpeg',
    '/images/film/film2.jpeg',
    '/images/film/film3.jpeg',
    '/images/film/film4.jpeg',
    '/images/film/film5.jpeg',
    '/images/film/film6.jpeg',
    '/images/film/film7.jpeg',
    '/images/film/film8.jpeg',
    '/images/film/film9.jpeg',
    '/images/film/film10.jpeg',
    '/images/film/film11.jpeg',
    '/images/film/film12.jpeg',
  ],
];
